[tool.poetry]
name = "google-docs-listener"
version = "0.1.0"
description = ""
authors = ["fvergaracl <fvergaracl@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
